version: '3.1'

services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - devops-tech-challenge
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - challenge-network
    ports:
      - 80:80
  devops-tech-challenge:
    image: devops-tech-challenge
    env_file:
      - ./.env
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      challenge-network:
        aliases:
          - devops-challenge

networks: 
  challenge-network: