version: '3.1'

services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - devops-tech-challenge
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - challenge-network
    ports:
      - 80:80
  devops-tech-challenge:
    image: devops-tech-challenge
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - SKIES_API_KEY=$SKIES_API_KEY
      - PYTHON_ENV=proxied
    networks:
      challenge-network:
        aliases:
          - devops-challenge

networks: 
  challenge-network: